import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";
import AppWalletProvider from "@/components/AppWalletProvider";
 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <AppWalletProvider>{children}</AppWalletProvider>
        <Footer />
      </body>
    </html>
  );
}
